### ISSUE TITLE
Peer review - Repository

### ISSUE THREAD

**Issue by veerleprins** [sanneduinkerx/web-app-from-scratch-2021#1]
- There is a description at the top right of the repository ✅ , only this is the description of the forked repository of Web App From Scratch. So maybe you can write a specific description for your repo here 😄 
- The repo is open for issues! ✅ 
- It contains a gitignore ✅ , but it only contains the notes.md and not all other files that are not needed for your specific application. Maybe you can put examples folder etc. in your gitignore 😄 
- The concept has not yet been described in the README. In the README you can describe everything about your project, including the API you are using. It is still missing 😄 

### Here is a little checklist for how to fix this: 

- [x] Add a specific description 
- [ ] Add files in your gitignore that are of no importance to your repo 
- [x]  Write a README stating which API you are using

**Comment by sanneduinkerx** [comment]
Thanks! Will fix this :)
