### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by victorboucher** [sanneduinkerx/web-app-from-scratch-2021#2]
### Algemeen:
- Ik zou in je .gitignore bestand nog even '.DS_Store' toevoegen en eventueel '.vscode' aangezien je deze bestanden waarschijnlijk niet in je repo wilt hebben
- Je moet op een gegeven moment zelf de readme schrijven en hierin ook je API beschrijven

### Code:
- Je selecteert je body element met een querySelector, maar je zou ook gewoon document.body kunnen gebruiken. Dit is netter en korter. Alleen wil je waarschijnlijk uiteindelijk niet al je albums direct in je body zetten maar in een aparte container.
- Het binnenhalen van de data uit de API doe je netjes via de XMLHttpRequest, maar je zou misschien kunnen kijken of dit netter is om te doen met de 'fetch api'. Dan werk je met promises en wordt je code een stuk netter naar mijn mening. Maar in principe doet het hetzelfde in jouw geval.
- Je gebruikt een ES5 functie (function()) en een ES6 functie (arrow function =>). Ik zie hier geen reden voor bij jouw code, dus misschien is het slim om te kijken of je alles op dezelfde manier aan kan pakken.
- Je gebruikt overal var om variabelen aan te maken, dit is ook de ES5 manier om variabelen aan te maken. In ES6 gebruiken we alleen const en let. Misschien is het slim om te kijken of je niet liever aan de slag gaat met alles op de ES6 manier te doen.
- De url bestaat uit verschillende variabelen die je mee kunt geven, zoals de artist en de api_key. Ik denk dat het netjes is als je deze dingen opslaat in een andere variabele en ze dan in de url 'plakt'. Hier een voorbeeld:

```javascript
const method = 'artist.gettopalbums'
const artist = 'acdc'
const apiKey= '9445b881096d29d7c6de9f9d2eb6b50d'
const url = `https://ws.audioscrobbler.com/2.0/?method=${method}&artist=${artist}&api_key=${apiKey}&format=json`
```

De pagina ziet er al mooi uit en het werkt in ieder geval. Lekker bezig, ga zo door! 😸

**Comment by lisaoude** [comment]
const endpoint = 'https://api.giphy.com/v1/gifs/search?q='
    const key = 'JzbS3qH49ykiVKnHZx0z5M0gjNPVMbh3'
    const limit = 20
    const url = `${endpoint}${inputValue}&api_key=${key}&limit=${limit}`

**Comment by sanneduinkerx** [comment]
**Checklist om aan te passen** 

**Algemeen**
- [ ]  Ik zal de bestanden die ik niet op github wil in de .gitignore plaatsen, goede tip ik wist niet dat dat kon :) (Should have)
- [x] Readme zal ik nog schrijven met api beschrijving (Must have)

**Code**
- klopt inderdaad wil later de top albums in een container plaatsen
- [x] ik zal ernaar kijken om de fetch methode te gebruiken voor de api (should have)
- [x] Het valt me zelf nu pas op dat ik 2 verschillende manieren heb gebruikt, ik zal beter op consistentie letten (Must have)
- [x] Ik zal de var naar const overzetten (must have)
- [x] Goede tip, zal dit toepassen met de url! (should have)
