### ISSUE TITLE
Peer review - Code

### ISSUE THREAD

**Issue by veerleprins** [sanneduinkerx/web-app-from-scratch-2021#3]
- Nice that I can already view all the top albums via github pages! ✅ 
- Your code looks clean! 👍 Maybe as a tip you can write separate functions instead of putting everything in 1 long if else statement 😄 
- You make good use of logical names!  ✅ 
- Perhaps as a tip you can also look at the different ECMAscript versions. You use 'var' and later you write an arrow function again. 😄 

Good luck! 😄  If you have any questions about my feedback, feel free to ask!

**Comment by sanneduinkerx** [comment]
Thank you, will look at that! 

**Checklist**
- [x] look at the if else statement (should have)
- [x] tip: different ECMAscript versions (must have)
