### ISSUE TITLE
Peer Review - Week 2

### ISSUE THREAD

**Issue by lisaoude** [sanneduinkerx/web-app-from-scratch-2021#4]
## General
- Your live link at the top of your repo works! 😄 
- Your added description is clear and tells me what I can do with your Web App. It might be nice to tell your user what to search for in your Web App as well, because I was first searching for actual album names, instead of artists' names.
- Great that you added pictures of your progress at weeks 1 and 2! 🔥 
- It might be nice to also incude what progress you made in words, so we can also read what you've accomplished each week! 😄 
- Great that you wrote your readme in English!
- When I use your Web App, sometimes an albumcover doesn't show up. I see either just the text and not the albumcover, or I see 'Null'. Can't figure out why either..

## Actor Diagram
- Looks good! 🔥 
- Might need some additions later on, when you're adding extra code and expanding your Web App.

## Interaction Diagram
- Very clear! 😄 

## HTML
- Semantically correct!
- Clear class names used as well!

## CSS
- Looks good! 🔥 
- Adding some more comments can help you and others understand your code better 😄 
- Great that you're giving credit where credit is due (gradient)!
- Just for consistency: sometimes your { curly brackets }  touch your selectors, and sometimes they don't. I would give them all just a tap on the spacebar!

## JS
- Working modules 🔥 
- Clear names used for each file!
- Your code looks clean!
- Easily understandable because of the comments you added! 😄

**Comment by sanneduinkerx** [comment]
Thankyou! i'll look at it! :)

**To Do**
- [x] give more feedback to user what to search for (must have)
- [x] Fix the albums that don't show a name or albumcover (should have)
- [x] consistency + comments in CSS (could have)
