### ISSUE TITLE
vrij 12 feb feedback lotte

### ISSUE THREAD

**Issue by Lottetekulve** [sanneduinkerx/web-app-from-scratch-2021#5]
Je read me is netjes mis wel nog wat info, wat voor stappen genomen deze week, wat wil ik nog gaan doen (behandel het echt als procesboek), laat een beetje zien van je content en codes. (kijk bij die van Sharon die is vrij overzichtelijk en duidelijk.) Je code ziet er goed uit, ik heb t idee dat je goed opweg bent. Ik heb alleen als ik jou live demo open, dat je website geen content laat zien. Idk of je hier nog mee bezig bent, maar is wel leuk om van te voren bv meest populaire muziek te zien of iets in die richting.
<img width="1680" alt="Schermafbeelding 2021-02-12 om 10 39 46" src="https://user-images.githubusercontent.com/78353514/107752154-a6cf9300-6d1e-11eb-82b6-143f3756d7dc.png">

Verder zou ik graag op een album willen klikken en dan meer info zien. :) Maar lekker bezig ga zo door vooral !

**Comment by sanneduinkerx** [comment]
Dankje!

**To Do**
- [x] Goed mijn proces laten zien met content EN code.
- [x] Beginpagina, alvast wat content laten zien met bijvoorbeeld populairste albums.
- [x] Detailpagina van een album
