### ISSUE TITLE
Consistent comment writing🤓🤓

### ISSUE THREAD

**Issue by Chazzers** [sanneduinkerx/web-app-from-scratch-2021#6]
https://github.com/sanneduinkerx/web-app-from-scratch-2021/blob/4c2196df4a0dd98c1b15adc91cd760ad67d1cadb/js/modules/api.js#L4-L13

Here you use writing comments above a piece of code and right next to it. Try to keep it consistent by always writing it above the piece of code. It's a bit cleaner that way

**Comment by sanneduinkerx** [comment]
Thankyou for the tip! I will look into that :D

- [x] Comments above a line of code
