### ISSUE TITLE
Writing a README.md🤓🤓

### ISSUE THREAD

**Issue by Chazzers** [sanneduinkerx/web-app-from-scratch-2021#7]
So usually you have the following things in a README:

1. The description of your application
2. Description of API
3. In this case an actor and interaction diagram
4. Installation guide of the application
5. Link to your wiki (In which you document the details of your app and your process)
6. Acknowledgments (Shoutouts to everyone that helped you make this application)

Since it's not necessary for someone that is going to use this app to know the process behind it, you don't need it in your README

**Comment by sanneduinkerx** [comment]
Good tip, will look at it! :)
